defaults:
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none
  - _self_

data:
  raw:
    calendar: ./data/raw/calendar.csv
    sales_history: ./data/raw/sales_history.csv
    prices_promos: ./data/raw/prices_promos.csv
    stores: ./data/raw/stores.csv
    suppliers: ./data/raw/suppliers.csv
    skus: ./data/raw/skus.csv
    initial_inventory: ./data/raw/initial_inventory.csv
  processed:
    path: ./data/processed/processed_data.csv
  features:
    path: ./data/features/features.csv

model:
  name: deepar
  horizon: 4
  dir: ./models/gluonts_model
  # Hyperparameters
  context_length: 26
  epochs: 50
  num_layers: 2
  hidden_size: 40

tuning:
  n_trials: 10
